#!/usr/bin/env bash
export ELECTRON_IS_DEV=0
cd /opt/CocoMusic/dist/electron
case "$(id -u)" in
0) electron main.js --no-sandbox "$@" ;;
*)
    electron main.js "$@"
    case "$?" in
    0) ;;
    *) electron main.js --no-sandbox "$@" ;;
    esac
    ;;
esac
