FROM debian:buster

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               autoconf \
               automake \
               build-essential \
               cdbs \
               cmake \
               curl \
               devscripts \
               equivs \
               fakeroot \
               meson \
    # Install the same Node.js version as the latest Electron uses
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" >> /etc/apt/sources.list \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs yarn \
    && apt-get clean \
    # Install Rust toolchains
    && curl https://sh.rustup.rs -s | sh -s -- --default-toolchain stable -y \
    && cp $HOME/.cargo/bin/* /usr/bin/ \
    && rm -rf /tmp/* /var/tmp/*
