FROM debian:buster

RUN set -ex \
    && dpkg --add-architecture mips64el                        \
    && apt-get update                                          \
    && apt-get install -y --no-install-recommends              \
        autoconf                                               \
        automake                                               \
        autotools-dev                                          \
        bc                                                     \
        binfmt-support                                         \
        binutils-multiarch                                     \
        binutils-multiarch-dev                                 \
        build-essential                                        \
        cdbs                                                   \
        cmake                                                  \
        crossbuild-essential-mips64el                          \
        curl                                                   \
        devscripts                                             \
        equivs                                                 \
        fakeroot                                               \
        libtool                                                \
        llvm                                                   \
        meson                                                  \
        multistrap                                             \
        qemu                                                   \
        qemu-user-static                                       \
    && apt-get install -y libc6:mips64el  libstdc++6:mips64el  \
    && apt-get clean                                           \
    && rm -rf /tmp/* /var/tmp/*


# Create symlinks for triple and set default CROSS_TRIPLE
ENV CROSS_TRIPLE=mips64el-linux-gnuabi64

RUN mkdir -p /usr/x86_64-linux-gnu;                                                             \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//") ]; then  \
        ln -s $bin /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//");      \
      fi;                                                                                       \
    done;                                                                                       \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/cc ]; then                                             \
        ln -s gcc /usr/${CROSS_TRIPLE}/bin/cc;                                                  \
      fi;                                                                                       \
    done

