FROM debian:buster

RUN set -ex \
    && dpkg --add-architecture i386                            \
    && apt-get update                                          \
    && apt-get install -y --no-install-recommends              \
        autoconf                                               \
        automake                                               \
        autotools-dev                                          \
        bc                                                     \
        binfmt-support                                         \
        binutils-multiarch                                     \
        binutils-multiarch-dev                                 \
        build-essential                                        \
        cdbs                                                   \
        cmake                                                  \
        crossbuild-essential-i386                              \
        curl                                                   \
        devscripts                                             \
        equivs                                                 \
        fakeroot                                               \
        libtool                                                \
        llvm                                                   \
        meson                                                  \
        multistrap                                             \
        qemu                                                   \
        qemu-user-static                                       \
        valac                                                  \
    && apt-get install -y libc6:i386 libstdc++6:i386           \
                          libqt5widgets5:i386 libgtk-3-0:i386  \
    # Install the same Node.js version as the latest Electron uses
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb [arch=amd64] https://dl.yarnpkg.com/debian/ stable main" >> /etc/apt/sources.list \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs yarn                          \
    && apt-get clean


# Create symlinks for triple and set default CROSS_TRIPLE
ENV CROSS_TRIPLE=i686-linux-gnu

RUN mkdir -p /usr/x86_64-linux-gnu;                                                             \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//") ]; then  \
        ln -s $bin /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//");      \
      fi;                                                                                       \
    done;                                                                                       \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/cc ]; then                                             \
        ln -s gcc /usr/${CROSS_TRIPLE}/bin/cc;                                                  \
      fi;                                                                                       \
    done

