FROM debian:bookworm

RUN set -ex \
    && dpkg --add-architecture arm64                           \
    && apt-get update                                          \
    && apt-get install -y --no-install-recommends              \
        autoconf                                               \
        automake                                               \
        autotools-dev                                          \
        bc                                                     \
        binfmt-support                                         \
        binutils-multiarch                                     \
        binutils-multiarch-dev                                 \
        build-essential                                        \
        cdbs                                                   \
        cmake                                                  \
        crossbuild-essential-arm64                             \
        curl                                                   \
        devscripts                                             \
        equivs                                                 \
        fakeroot                                               \
        libtool                                                \
        llvm                                                   \
        meson                                                  \
        multistrap                                             \
    && apt-get install -y libc6:arm64 libstdc++6:arm64         \
        libqt5widgets5:arm64 libgtk-3-0:arm64 libgtk-4-1:arm64 \
    # Install Rust toolchains
    && curl https://sh.rustup.rs -s | sh -s -- --default-toolchain stable -y \
    && cp $HOME/.cargo/bin/* /usr/bin/                         \
    && rustup target add aarch64-unknown-linux-gnu             \
    && apt-get clean


# Create symlinks for triple and set default CROSS_TRIPLE
ENV CROSS_TRIPLE=aarch64-linux-gnu

RUN mkdir -p /usr/x86_64-linux-gnu;                                                             \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//") ]; then  \
        ln -s $bin /usr/${CROSS_TRIPLE}/bin/$(basename $bin | sed "s/${CROSS_TRIPLE}-//");      \
      fi;                                                                                       \
    done;                                                                                       \
    for bin in /usr/bin/${CROSS_TRIPLE}-*; do                                                   \
      if [ ! -f /usr/${CROSS_TRIPLE}/bin/cc ]; then                                             \
        ln -s gcc /usr/${CROSS_TRIPLE}/bin/cc;                                                  \
      fi;                                                                                       \
    done

