#!/bin/sh

set -e

# Link ripgrep
ln -sf /usr/bin/rp /opt/marktext/node_modules/vscode-ripgrep/bin/

# Update icons
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/marktext.png
	fi
fi

