
name: Build

on:
  push:
    branches: [ develop ]
  schedule:
    # Run on UTC 5:30 everyday
    - cron: '30 5 * * *'




jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEBIAN_RELEASE: bookworm
      DEBIAN_ARCH: amd64
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      ENCRYPT_PASSWORD: ${{ secrets.ENCRYPT_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Decrypt gpg key
        run: |-
          openssl enc -des3 -d -in mysec.gpg.encrypted -out mysec.gpg -k ${ENCRYPT_PASSWORD}
          gpg --allow-secret-key-import --import mysec.gpg

      - name: Cache docker image
        uses: actions/cache@v2
        with:
          path: docker_images
          key: ${{ runner.os }}-build
          

      - name: Build docker image
        run: |-
          if [ -f docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz ]; then
            gzip -dc docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz | docker load
          else
            docker build -t docker-deb-builder:${DEBIAN_RELEASE}-${DEBIAN_ARCH} -f docker-deb-builder/Dockerfile-debian-${DEBIAN_RELEASE}-${DEBIAN_ARCH} .
          fi

      - name: Install reprepro
        run: sudo apt-get install reprepro

      - name: Build and upload packages
        run: ./scan-and-build.sh

      - name: Summary
        run: ./summary.sh
